# Generated by Django 5.2.1 on 2025-06-04 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_etude', models.CharField(choices=[('informatique', 'Informatique'), ('medecine', 'Médecine'), ('ingenierie', 'Ingénierie'), ('economie', 'Économie'), ('droit', 'Droit'), ('lettres', 'Lettres et Langues'), ('sciences', 'Sciences Exactes'), ('sciences_sociales', 'Sciences Sociales'), ('arts', 'Arts et Design'), ('agriculture', 'Agriculture')], max_length=50, verbose_name="Domaine d'étude")),
                ('type_diplome', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('ingenieur', 'Ingénieur'), ('technicien_superieur', 'Technicien Supérieur'), ('formation_professionnelle', 'Formation Professionnelle')], max_length=50, verbose_name='Type de diplôme')),
                ('interet', models.CharField(choices=[('recherche', 'Recherche Académique'), ('industrie', 'Secteur Industriel'), ('enseignement', 'Enseignement'), ('entrepreneuriat', 'Entrepreneuriat'), ('fonction_publique', 'Fonction Publique'), ('secteur_prive', 'Secteur Privé'), ('consulting', 'Conseil'), ('international', 'Organisations Internationales')], max_length=50, verbose_name='Intérêt professionnel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateurs',
            },
        ),
    ]
